// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int num = Integer.parseInt(args[0]);
        int above = 0;
		int belowOrEqual = 0;
		for (int i = 0; i < num; i++){
			double r = Math.random();
		if (r > 0.5){
			above++;
		} else {
			belowOrEqual++;
		}
		} 
		System.out.println("> 0.5: " + above + " times");
		System.out.println("<= 0.5: " + belowOrEqual + " times");

		if (above == 0 || belowOrEqual == 0){

		} else {
			double ratio = (double) above / belowOrEqual;
			System.out.println("Ratio: " + ratio);
		}
    }
}
